name: Release
on:
  push:
    branches:
      - development
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      # install the latest of v11 to fix npm ci issues
      - run: npm i -g npm@11
      - run: npm ci
      - run: npm run lint
      - run: npm run validate
      - run: npm test
      - name: Install Additional Dependencies
        run: npm install @semantic-release/git @semantic-release/changelog
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
